networks:
  ecoround-network:

services:
  ecoroundotp:
    image: ponleou/ecoroundotp:latest
    container_name: ecoroundotp
    networks:
      - ecoround-network
    ports:
      - "127.0.0.1:8080:8080"

  ecoroundflask:
    image: ponleou/ecoroundflask:latest
    container_name: ecoroundflask
    networks:
      - ecoround-network
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      - ORS_API_KEY=${ORS_API_KEY}
      - OTP_SERVER=ecoroundotp:8080

  ecoroundtunnel:
    image: node:23-alpine
    container_name: ecoroundtunnel
    networks:
      - ecoround-network
    environment:
      - APP_SUBDOMAIN=${PROD_SUBDOMAIN}
    command: sh -c "npm install -g localtunnel && localtunnel --port 5000 --subdomain $APP_SUBDOMAIN"
    restart: unless-stopped
