networks:
  ecoround-network:

services:
  ecoroundotp:
    image: ponleou/ecoroundotp:latest
    container_name: ecoroundotp
    networks:
      - ecoround-network

  ecoroundflask:
    image: ponleou/ecoroundflask:latest
    container_name: ecoroundflask
    networks:
      - ecoround-network
    environment:
      - ORS_API_KEY=${ORS_API_KEY}
      - OTP_SERVER=ecoroundotp:8080
    volumes:
      - ./logs:/app/logs

  ecoroundtunnel:
    image: node:23
    container_name: ecoroundtunnel
    networks:
      - ecoround-network
    environment:
      - PROD_SUBDOMAIN=${PROD_SUBDOMAIN}
    command: sh -c "npx localtunnel --port 5000 --local-host ecoroundflask --subdomain $PROD_SUBDOMAIN"
    restart: unless-stopped
